# Préparation des données network

In [1]:
import pandas as pd
import os
from pickleshare import PickleShareDB

## Chargement des données

In [2]:
df_net_1_load = pd.read_csv('../datasets/Network datatset/csv/attack_1.csv')
df_net_2_load = pd.read_csv('../datasets/Network datatset/csv/attack_2.csv')
df_net_3_load = pd.read_csv('../datasets/Network datatset/csv/attack_3.csv')
df_net_4_load = pd.read_csv('../datasets/Network datatset/csv/attack_4.csv')
df_net_norm_load = pd.read_csv('../datasets/Network datatset/csv/normal.csv')

In [3]:
df_net_1 = df_net_1_load.copy()
df_net_2 = df_net_2_load.copy()
df_net_3 = df_net_3_load.copy()
df_net_4 = df_net_4_load.copy()
df_net_norm = df_net_norm_load.copy()

## Enregistrement et ouverture avec PickleShare si besoin

In [4]:
"""
data_dir = '../prep_data' 
os.makedirs(data_dir, exist_ok=True)
db = PickleShareDB(os.path.join(data_dir, 'kity'))

db['net_attack_1'] = df_net_1_load
db['net_attack_2'] = df_net_2_load
db['net_attack_3'] = df_net_3_load
db['net_attack_4'] = df_net_4_load
db['net_norm'] = df_net_norm_load
"""

"\ndata_dir = '../prep_data' \nos.makedirs(data_dir, exist_ok=True)\ndb = PickleShareDB(os.path.join(data_dir, 'kity'))\n\ndb['net_attack_1'] = df_net_1_load\ndb['net_attack_2'] = df_net_2_load\ndb['net_attack_3'] = df_net_3_load\ndb['net_attack_4'] = df_net_4_load\ndb['net_norm'] = df_net_norm_load\n"

In [5]:
"""
df_net_1 = db['net_attack_1']
df_net_2 = db['net_attack_2']
df_net_3 = db['net_attack_3']
df_net_4 = db['net_attack_4']
df_net_norm = db['net_norm']
"""

"\ndf_net_1 = db['net_attack_1']\ndf_net_2 = db['net_attack_2']\ndf_net_3 = db['net_attack_3']\ndf_net_4 = db['net_attack_4']\ndf_net_norm = db['net_norm']\n"

## Observation des données (1)

In [6]:
df_all = [df_net_1, df_net_2, df_net_3, df_net_4, df_net_norm]
df_nom = ['df_net_1', 'df_net_2', 'df_net_3', 'df_net_4', 'df_net_norm']

In [7]:
df_net_1.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 18:23:28.385003,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,56667.0,502.0,Modbus,11000.0,66,Read Coils Request,0.0,0.0,NaN,0,normal
1,2021-04-09 18:23:28.385005,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,56666.0,502.0,Modbus,11000.0,66,Read Coils Request,1.0,0.0,NaN,0,normal
2,2021-04-09 18:23:28.385006,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,56668.0,502.0,Modbus,11000.0,66,Read Coils Request,2.0,0.0,NaN,0,normal
3,2021-04-09 18:23:28.385484,0a:fe:ec:47:74:fb,74:46:a0:bd:a7:1b,84.3.251.102,84.3.251.20,502.0,56667.0,Modbus,11000.0,64,Read Coils Response,0.0,0.0,[0],0,normal
4,2021-04-09 18:23:28.385486,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,56668.0,Modbus,11000.0,64,Read Coils Response,0.0,1.0,[0],0,normal

Le dataset réseau contient des informations détaillées sur le trafic Modbus :
- adresses MAC et IP source et destination
- les ports utilisés
- le protocole de communication
- des flags TCP
- la taille des paquets 
- codes fonctionnels Modbus
- le nombre de paquets provenant de la même source ou destination
- la réponse du protocole Modbub
- le label indiquant si le paquet est normal ou malveillant

In [8]:
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i].columns}")

df_net_1 : Index(['Time', ' mac_s', ' mac_d', ' ip_s', ' ip_d', ' sport', ' dport',
       ' proto', ' flags', ' size', ' modbus_fn', ' n_pkt_src', ' n_pkt_dst',
       ' modbus_response', ' label_n', ' label'],
      dtype='object')
df_net_2 : Index(['Time', ' mac_s', ' mac_d', ' ip_s', ' ip_d', ' sport', ' dport',
       ' proto', ' flags', ' size', ' modbus_fn', ' n_pkt_src', ' n_pkt_dst',
       ' modbus_response', ' label_n', ' label'],
      dtype='object')
df_net_3 : Index(['Time', ' mac_s', ' mac_d', ' ip_s', ' ip_d', ' sport', ' dport',
       ' proto', ' flags', ' size', ' modbus_fn', ' n_pkt_src', ' n_pkt_dst',
       ' modbus_response', ' label_n', ' label'],
      dtype='object')
df_net_4 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'modbus_response', 'n_pkt_src',
       'n_pkt_dst', 'label_n', 'label'],
      dtype='object')
df_net_norm : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')

Les noms des colonnes des 3 premiers datasets contiennent des espaces au début, nous les supprimerons.  
De plus, les colonnes ne sont pas ordonnées de la même manière.

In [9]:
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i].shape}")

df_net_1 : (5527409, 16)
df_net_2 : (5159469, 16)
df_net_3 : (5862547, 16)
df_net_4 : (5522490, 16)
df_net_norm : (7757289, 16)

Les fichiers d'attaque font la même taille, et le fichier avec des données normales contient plus de données.

In [10]:
df_all[0].head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 18:23:28.385003,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,56667.0,502.0,Modbus,11000.0,66,Read Coils Request,0.0,0.0,NaN,0,normal
1,2021-04-09 18:23:28.385005,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,56666.0,502.0,Modbus,11000.0,66,Read Coils Request,1.0,0.0,NaN,0,normal
2,2021-04-09 18:23:28.385006,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,56668.0,502.0,Modbus,11000.0,66,Read Coils Request,2.0,0.0,NaN,0,normal
3,2021-04-09 18:23:28.385484,0a:fe:ec:47:74:fb,74:46:a0:bd:a7:1b,84.3.251.102,84.3.251.20,502.0,56667.0,Modbus,11000.0,64,Read Coils Response,0.0,0.0,[0],0,normal
4,2021-04-09 18:23:28.385486,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,56668.0,Modbus,11000.0,64,Read Coils Response,0.0,1.0,[0],0,normal

## Nettoyage (1)

### Harmonisation noms colonnes

In [11]:
for df in df_all:
    df.columns = df.columns.str.strip()

In [12]:
# Vérification
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i].columns}")

df_net_1 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_2 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_3 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_4 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'modbus_response', 'n_pkt_src',
       'n_pkt_dst', 'label_n', 'label'],
      dtype='object')
df_net_norm : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')

### Ordre colonnes

In [13]:
columns_order = ['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto', 'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 'modbus_response', 'label_n', 'label']
df_all = [df[columns_order] for df in df_all]

In [14]:
# Vérification
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i].columns}")

df_net_1 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_2 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_3 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_4 : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')
df_net_norm : Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'label'],
      dtype='object')

## Observation des données (2)

### Colonne label et label_n

In [15]:
for i in range(len(df_all)):
    print(f"\n{df_nom[i]} : {df_all[i][['label', 'label_n']].value_counts()}")

df_net_1 : label           label_n
normal          0          3687410
MITM            1          1214098
physical fault  1           625691
anomaly         1              210
Name: count, dtype: int64

df_net_2 : label           label_n
normal          0          4093168
DoS             1           571875
physical fault  1           277282
MITM            1           217009
anomaly         1              105
scan            1               30
Name: count, dtype: int64

df_net_3 : label           label_n
DoS             1          3194711
normal          0          2070555
physical fault  1           344244
MITM            1           252963
anomaly         1               74
Name: count, dtype: int64

df_net_4 : label           label_n
normal          0          2844877
DoS             1          1904956
MITM            1           471339
physical fault  1           301287
scan            1               31
Name: count, dtype: int64

df_net_norm : label   label_n
normal  0          7757289
Name: count, dtype: int64

On peut voir que label est à 0 lors d'une situation normale, et à 1 lors des attaques.  
C'est ce qu'il fallait, pas besoin de nettoyer cela.

Le fichier normal ne contient pas de label = 1, contrairement aux fichiers d'attaque.  
Le fichier est donc bien un fichier représentant le fonctionnement normale des échanges réseau.

Les différentes valeurs de label :  
- normal : pas d'attaque
- MITM (= Man-in-the-Middle) : L'attaquant intercepte et peut modifier les communications entre deux appareils.
- physical fault : Anomalies physiques non causée par une cyberattaque \
--> Normalement non détectables dans les données réseau
- anomaly : autre anomalies non MITM et pas un défaut physique.
- DoS (=Denial of service) : L'attaquant inonde le service de requêtes/paquets pour le surcharger et le rendre indisponible.
- scan : L'attaquant cherche à identifier les ports ouverts et les vulnérabilités potentielles avant une attaque.

In [16]:
for i in range(len(df_all)):
    print(f"\n{df_nom[i]} :")
    column_types = ', '.join([f"{col} ({dtype})" for col, dtype in zip(df_all[i].columns, df_all[i].dtypes)])
    print(column_types)

df_net_1 :
Time (object), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (float64), dport (float64), proto (object), flags (float64), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (int64), label (object)

df_net_2 :
Time (object), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (float64), dport (float64), proto (object), flags (float64), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (int64), label (object)

df_net_3 :
Time (object), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (float64), dport (float64), proto (object), flags (float64), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (int64), label (object)

df_net_4 :
Time (object), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (float64), dport (float64), proto (object), flags (float64), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (int64), label (object)

df_net_norm :
Time (object), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (int64), dport (int64), proto (object), flags (int64), size (int64), modbus_fn (object), n_pkt_src (int64), n_pkt_dst (int64), modbus_response (object), label_n (int64), label (object)

In [17]:
for i in range(len(df_all)):
    print(f"\n{df_nom[i]} :")
    for col in ['sport', 'dport', 'flags', 'n_pkt_src', 'n_pkt_dst']:
        has_floats = df_all[i][col].apply(lambda x: x != int(x) if not pd.isna(x) else False).any()
        if has_floats:
            print(f"'{col}' --> float")
        else:
            print(f"'{col}' --> int")

df_net_1 :
'sport' --> int
'dport' --> int
'flags' --> int
'n_pkt_src' --> int
'n_pkt_dst' --> int

df_net_2 :
'sport' --> int
'dport' --> int
'flags' --> int
'n_pkt_src' --> int
'n_pkt_dst' --> int

df_net_3 :
'sport' --> int
'dport' --> int
'flags' --> int
'n_pkt_src' --> int
'n_pkt_dst' --> int

df_net_4 :
'sport' --> int
'dport' --> int
'flags' --> int
'n_pkt_src' --> int
'n_pkt_dst' --> int

df_net_norm :
'sport' --> int
'dport' --> int
'flags' --> int
'n_pkt_src' --> int
'n_pkt_dst' --> int

Dans le dataset avec les données normales, les colonnes sport, dport, flags, n_pkt_src, et n_pkt_dst sont au format int64 alors que pour les autres datasets, ce sont des float64.  
Aucune de ces colonnes ne contient de chiffre après la virgule, nous les convertirons en int64.

De même pour la colonne Time, nous la convertirons en DateTime.

Et pour les colonnes de labels :
- label_n est de type64 alors que ses valeurs sont 0 ou 1, nous allons donc convertir en booléen.
- label est de type object mais c'est une categorie, nous allons convertir en category.

## Nettoyage (2)

### Modification des types

In [ ]:
# Vérification des valeurs manquantes avant
for i, df in enumerate(df_all, 0):
    print(f"Valeurs nulles dans {df_nom[i]} :")
    null_counts = df.isnull().sum()
    print(null_counts)
    print()

Valeurs nulles dans df_net_1 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   475
ip_d                   475
sport                  515
dport                  515
proto                    0
flags                  515
size                     0
modbus_fn           153123
n_pkt_src              475
n_pkt_dst              475
modbus_response    2840182
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_2 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   276
ip_d                   276
sport               385383
dport               385383
proto                    0
flags               385383
size                     0
modbus_fn           539517
n_pkt_src              276
n_pkt_dst              276
modbus_response    2849430
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_3 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   189
ip_d                   189
sport              3066837
dport              3066837
proto                    0
flags              3066837
size                     0
modbus_fn          3143940
n_pkt_src              189
n_pkt_dst              189
modbus_response    4503169
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_4 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   439
ip_d                   439
sport              1172305
dport              1172305
proto                    0
flags              1172305
size                     0
modbus_fn          1751892
n_pkt_src              439
n_pkt_dst              439
modbus_response    3637071
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_norm :
Time                     0
mac_s                    0
mac_d                    0
ip_s                     0
ip_d                     0
sport                    0
dport                    0
proto                    0
flags                    0
size                     0
modbus_fn           210243
n_pkt_src                0
n_pkt_dst                0
modbus_response    3983640
label_n                  0
label                    0
dtype: int64

In [19]:
for i, df in enumerate(df_all):
    df['label_n'] = df['label_n'].astype('bool')
    df['label'] = df['label'].astype('category')

In [21]:
columns_to_convert = ['sport', 'dport', 'flags', 'n_pkt_src', 'n_pkt_dst']

for i in range(len(df_all)):
    for col in columns_to_convert:
        df_all[i][col] = df_all[i][col].astype('Int64') # ok pour les valeurs manquantes

In [22]:
for i in range(len(df_all)):
    df_all[i]['Time'] = pd.to_datetime(df_all[i]['Time'], format='mixed')

In [23]:
# Verification
for i in range(len(df_all)):
    print(f"\n{df_nom[i]} :")
    column_types = ', '.join([f"{col} ({dtype})" for col, dtype in zip(df_all[i].columns, df_all[i].dtypes)])
    print(column_types)

df_net_1 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (Int64), dport (Int64), proto (object), flags (Int64), size (int64), modbus_fn (object), n_pkt_src (Int64), n_pkt_dst (Int64), modbus_response (object), label_n (bool), label (category)

df_net_2 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (Int64), dport (Int64), proto (object), flags (Int64), size (int64), modbus_fn (object), n_pkt_src (Int64), n_pkt_dst (Int64), modbus_response (object), label_n (bool), label (category)

df_net_3 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (Int64), dport (Int64), proto (object), flags (Int64), size (int64), modbus_fn (object), n_pkt_src (Int64), n_pkt_dst (Int64), modbus_response (object), label_n (bool), label (category)

df_net_4 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (Int64), dport (Int64), proto (object), flags (Int64), size (int64), modbus_fn (object), n_pkt_src (Int64), n_pkt_dst (Int64), modbus_response (object), label_n (bool), label (category)

df_net_norm :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (Int64), dport (Int64), proto (object), flags (Int64), size (int64), modbus_fn (object), n_pkt_src (Int64), n_pkt_dst (Int64), modbus_response (object), label_n (bool), label (category)

In [24]:
# Vérification des valeurs manquantes après
for i, df in enumerate(df_all, 0):
    print(f"Valeurs nulles dans {df_nom[i]} :")
    null_counts = df.isnull().sum()
    print(null_counts)
    print()

Valeurs nulles dans df_net_1 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   475
ip_d                   475
sport                  515
dport                  515
proto                    0
flags                  515
size                     0
modbus_fn           153123
n_pkt_src              475
n_pkt_dst              475
modbus_response    2840182
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_2 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   276
ip_d                   276
sport               385383
dport               385383
proto                    0
flags               385383
size                     0
modbus_fn           539517
n_pkt_src              276
n_pkt_dst              276
modbus_response    2849430
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_3 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   189
ip_d                   189
sport              3066837
dport              3066837
proto                    0
flags              3066837
size                     0
modbus_fn          3143940
n_pkt_src              189
n_pkt_dst              189
modbus_response    4503169
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_4 :
Time                     0
mac_s                    0
mac_d                    0
ip_s                   439
ip_d                   439
sport              1172305
dport              1172305
proto                    0
flags              1172305
size                     0
modbus_fn          1751892
n_pkt_src              439
n_pkt_dst              439
modbus_response    3637071
label_n                  0
label                    0
dtype: int64

Valeurs nulles dans df_net_norm :
Time                     0
mac_s                    0
mac_d                    0
ip_s                     0
ip_d                     0
sport                    0
dport                    0
proto                    0
flags                    0
size                     0
modbus_fn           210243
n_pkt_src                0
n_pkt_dst                0
modbus_response    3983640
label_n                  0
label                    0
dtype: int64

## Observation des données (3)

### Observation des types

Les colonnes sport, dport et flags sont actuellement représenteés comme des colonnes avec des valeurs continues.  
Cependant, cela n'a pas de sens.

In [26]:
# nombre de valeurs unique par colonne pour chaque dataset
columns_of_interest = ['dport', 'sport', 'flags']
for i in range(len(df_all)):
    print(f"{df_nom[i]} :")
    for col in columns_of_interest:
        print(f"- '{col}' : {df_all[i][col].nunique()} valeurs uniques")
    print()

df_net_1 :
- 'dport' : 8441 valeurs uniques
- 'sport' : 8445 valeurs uniques
- 'flags' : 7 valeurs uniques

df_net_2 :
- 'dport' : 9475 valeurs uniques
- 'sport' : 23748 valeurs uniques
- 'flags' : 12 valeurs uniques

df_net_3 :
- 'dport' : 5276 valeurs uniques
- 'sport' : 5284 valeurs uniques
- 'flags' : 9 valeurs uniques

df_net_4 :
- 'dport' : 10205 valeurs uniques
- 'sport' : 65536 valeurs uniques
- 'flags' : 11 valeurs uniques

df_net_norm :
- 'dport' : 10261 valeurs uniques
- 'sport' : 10261 valeurs uniques
- 'flags' : 7 valeurs uniques

Les colonnes sport et dport ont entre 5000 et 10000 valeurs possibles différentes, il n'est donc pas possible de faire un One-Hot.  
Nous allons donc regrouper les IP par catégories : "System Ports (0-1023), User Ports (1024-49151), et the Dynamic and/or Private Ports (49152-65535)"  
Source : https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml

Pour la colonne flags, comme il y a moins de 10 valeurs possibles, nous les transformons en catégories, et nous ferons peut etre un one-hot plus tard avant les modèles.

## Nettoyage (3)

### Discrétisation des ports

In [27]:
def get_categorie_ports(port):
    if pd.isna(port):
        return "inconnu" # remplacement des valeurs manquantes
    if port < 1024:
        return "system_ports"
    elif port <= 49151:
        return "user_ports"
    else:
        return "dynamic/private_ports"

In [28]:
for i in range(len(df_all)):
    for col in ['sport', 'dport']:
        df_all[i][col] = df_all[i][col].apply(get_categorie_ports).astype('category')

In [29]:
df_all[0].head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 18:23:28.385003,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,dynamic/private_ports,system_ports,Modbus,11000,66,Read Coils Request,0,0,NaN,False,normal
1,2021-04-09 18:23:28.385005,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,11000,66,Read Coils Request,1,0,NaN,False,normal
2,2021-04-09 18:23:28.385006,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,11000,66,Read Coils Request,2,0,NaN,False,normal
3,2021-04-09 18:23:28.385484,0a:fe:ec:47:74:fb,74:46:a0:bd:a7:1b,84.3.251.102,84.3.251.20,system_ports,dynamic/private_ports,Modbus,11000,64,Read Coils Response,0,0,[0],False,normal
4,2021-04-09 18:23:28.385486,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,system_ports,dynamic/private_ports,Modbus,11000,64,Read Coils Response,0,1,[0],False,normal

In [30]:
# Répartition des valeurs 'sport'
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i][['sport']].value_counts()}")
    print()

df_net_1 : sport
system_ports             2755880
dynamic/private_ports    2717013
user_ports                 54001
inconnu                      515
Name: count, dtype: int64

df_net_2 : sport
system_ports             2370281
dynamic/private_ports    2335408
inconnu                   385383
user_ports                 68397
Name: count, dtype: int64

df_net_3 : sport
inconnu                  3066837
system_ports             1393971
dynamic/private_ports    1374699
user_ports                 27040
Name: count, dtype: int64

df_net_4 : sport
dynamic/private_ports    2032556
system_ports             1982069
inconnu                  1172305
user_ports                335560
Name: count, dtype: int64

df_net_norm : sport
system_ports             3868406
dynamic/private_ports    3814580
user_ports                 74303
Name: count, dtype: int64

In [31]:
# Répartition des valeurs 'dport'
for i in range(len(df_all)):
    print(f"{df_nom[i]} : {df_all[i][['dport']].value_counts()}")
    print()

df_net_1 : dport
system_ports             2771014
dynamic/private_ports    2710772
user_ports                 45108
inconnu                      515
Name: count, dtype: int64

df_net_2 : dport
system_ports             2403805
dynamic/private_ports    2329433
inconnu                   385383
user_ports                 40848
Name: count, dtype: int64

df_net_3 : dport
inconnu                  3066837
system_ports             1401739
dynamic/private_ports    1371443
user_ports                 22528
Name: count, dtype: int64

df_net_4 : dport
system_ports             2373231
dynamic/private_ports    1939598
inconnu                  1172305
user_ports                 37356
Name: count, dtype: int64

df_net_norm : dport
system_ports             3888883
dynamic/private_ports    3806034
user_ports                 62372
Name: count, dtype: int64

In [32]:
df_all[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5527409 entries, 0 to 5527408
Data columns (total 16 columns):
 #   Column           Dtype
---  ------           -----
 0   Time             datetime64[ns]
 1   mac_s            object
 2   mac_d            object
 3   ip_s             object
 4   ip_d             object
 5   sport            category
 6   dport            category
 7   proto            object
 8   flags            Int64
 9   size             int64
 10  modbus_fn        object
 11  n_pkt_src        Int64
 12  n_pkt_dst        Int64
 13  modbus_response  object
 14  label_n          bool
 15  label            category
dtypes: Int64(3), bool(1), category(3), datetime64[ns](1), int64(1), object(7)
memory usage: 542.9+ MB

### Transformation des flags en catégories

In [33]:
for i, df in enumerate(df_all):
    df['flags'] = df['label'].astype('category')

### One-hot de la colonne flags (faire plus tard)

In [34]:
#for i in range(len(df_all)):
#    df_all[i] = pd.get_dummies(df_all[i], columns=['flags'], prefix='flag')

In [35]:
#df_all[0].head()

Les colonnes créée ne sont pas forcément les même en fonction des datasets, car toutes les valeurs n'ètaient pas présentent dans tous les datasets.  
Nous ajoutons donc des colonnes avec False si elles n'y sont pas.

#### Ajout des colonnes non créées

In [36]:
#all_columns = set()
#for df in df_all:
#    flag_columns = [col for col in df.columns if col.startswith('flag')]
#    all_columns.update(flag_columns)
#all_columns = list(all_columns)

In [37]:
#print(all_columns)

In [38]:
#for i in range(len(df_all)):
#    manquantes = set(all_columns) - set(df_all[i].columns)
#    
#    for col in manquantes:
#        df_all[i][col] = False
#    
#    df_all[i] = df_all[i].reindex(columns=list(df_all[i].columns) + [col for col in all_columns if col not in df_all[i].columns])

In [39]:
# Check si les flags avec des valeurs manquantes ont bien des False dans toutes les colonnes
#columns_to_check = ['flag_0', 'flag_10100', 'flag_10', 'flag_10000', 'flag_11000010', 'flag_11001', 'flag_11000', 'flag_1', 'flag_101001', 'flag_10010', 'flag_100', 'flag_10001']
#
#for i in range(len(df_all)):
#    df = df_all[i]
#    false_count = (~df[columns_to_check].any(axis=1)).sum()
#    print(f"{df_nom[i]} : {false_count} = False")

In [40]:
#df_all[0].head()

# Observation des données (4)

In [ ]:
# Vérification des valeurs manquantes
for i, df in enumerate(df_all, 0):
    print(f"Valeurs nulles dans {df_nom[i]} :")
    null_counts = df.isnull().sum()
    print(null_counts[null_counts > 0]) # Affiche seulement les colonnes avec des valeurs nulles
    print()

Valeurs nulles dans df_net_1 :
ip_s                   475
ip_d                   475
modbus_fn           153123
n_pkt_src              475
n_pkt_dst              475
modbus_response    2840182
dtype: int64

Valeurs nulles dans df_net_2 :
ip_s                   276
ip_d                   276
modbus_fn           539517
n_pkt_src              276
n_pkt_dst              276
modbus_response    2849430
dtype: int64

Valeurs nulles dans df_net_3 :
ip_s                   189
ip_d                   189
modbus_fn          3143940
n_pkt_src              189
n_pkt_dst              189
modbus_response    4503169
dtype: int64

Valeurs nulles dans df_net_4 :
ip_s                   439
ip_d                   439
modbus_fn          1751892
n_pkt_src              439
n_pkt_dst              439
modbus_response    3637071
dtype: int64

Valeurs nulles dans df_net_5 :
modbus_fn           210243
modbus_response    3983640
dtype: int64

Les colonnes catégoriques ip_s, ip_d, modbus_fn, et modbus_response ont des valeurs manquantes.  
Nous allons remplacer ces valeurs manquantes par "Inconnue" pour ne pas perdre d'informations.

Pour les colonnes numériques n_pkt_src, et n_pkt_dst ayant des valeurs manquantes, nous allons remplacer par la médiane.

## Nettoyage (4)

In [42]:
for df in df_all:
    for col in ['ip_s', 'ip_d', 'modbus_fn', 'modbus_response']:
        df[col] = df[col].fillna("inconnue")
    for col in ['n_pkt_src', 'n_pkt_dst']: # La colonne redevient de type float
        df[col] = df[col].median()

In [ ]:
# Vérification des valeurs manquantes
for i, df in enumerate(df_all, 0):
    print(f"Valeurs nulles dans {df_nom[i]} :")
    null_counts = df.isnull().sum()
    print(null_counts[null_counts > 0]) # Affiche seulement les colonnes avec des valeurs nulles
    print()

Valeurs nulles dans df_net_1 :
Series([], dtype: int64)

Valeurs nulles dans df_net_2 :
Series([], dtype: int64)

Valeurs nulles dans df_net_3 :
Series([], dtype: int64)

Valeurs nulles dans df_net_4 :
Series([], dtype: int64)

Valeurs nulles dans df_net_5 :
Series([], dtype: int64)

## Enregistrement des données dans les datasets

In [44]:
df_net_1 = df_all[0]
df_net_2 = df_all[1]
df_net_3 = df_all[2]
df_net_4 = df_all[3]
df_net_norm = df_all[4]

## Données préparées

In [45]:
for i in range(len(df_all)):
    print(f"\n{df_nom[i]} :")
    column_types = ', '.join([f"{col} ({dtype})" for col, dtype in zip(df_all[i].columns, df_all[i].dtypes)])
    print(column_types)

df_net_1 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (category), dport (category), proto (object), flags (category), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (bool), label (category)

df_net_2 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (category), dport (category), proto (object), flags (category), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (bool), label (category)

df_net_3 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (category), dport (category), proto (object), flags (category), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (bool), label (category)

df_net_4 :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (category), dport (category), proto (object), flags (category), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (bool), label (category)

df_net_norm :
Time (datetime64[ns]), mac_s (object), mac_d (object), ip_s (object), ip_d (object), sport (category), dport (category), proto (object), flags (category), size (int64), modbus_fn (object), n_pkt_src (float64), n_pkt_dst (float64), modbus_response (object), label_n (bool), label (category)

In [46]:
df_net_1.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 18:23:28.385003,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,dynamic/private_ports,system_ports,Modbus,normal,66,Read Coils Request,19.0,19.0,inconnue,False,normal
1,2021-04-09 18:23:28.385005,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,normal,66,Read Coils Request,19.0,19.0,inconnue,False,normal
2,2021-04-09 18:23:28.385006,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,normal,66,Read Coils Request,19.0,19.0,inconnue,False,normal
3,2021-04-09 18:23:28.385484,0a:fe:ec:47:74:fb,74:46:a0:bd:a7:1b,84.3.251.102,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,64,Read Coils Response,19.0,19.0,[0],False,normal
4,2021-04-09 18:23:28.385486,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,64,Read Coils Response,19.0,19.0,[0],False,normal

In [47]:
df_net_2.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-19 15:37:19.989214,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,64,Read Coils Response,43.0,41.0,[0],False,normal
1,2021-04-19 15:37:19.990641,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,43.0,41.0,inconnue,False,normal
2,2021-04-19 15:37:19.990645,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,43.0,41.0,inconnue,False,normal
3,2021-04-19 15:37:19.990647,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,normal,66,Read Coils Request,43.0,41.0,inconnue,False,normal
4,2021-04-19 15:37:19.990943,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,65,Read Holding Registers Response,43.0,41.0,[0],False,normal

In [48]:
df_net_3.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 19:42:13.484804,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,64,Read Coils Response,90.0,90.0,[0],False,normal
1,2021-04-09 19:42:13.487062,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,90.0,90.0,inconnue,False,normal
2,2021-04-09 19:42:13.487078,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,90.0,90.0,inconnue,False,normal
3,2021-04-09 19:42:13.487079,74:46:a0:bd:a7:1b,00:80:f4:03:fb:12,84.3.251.20,84.3.251.18,dynamic/private_ports,system_ports,Modbus,normal,66,Read Coils Request,90.0,90.0,inconnue,False,normal
4,2021-04-09 19:42:13.487080,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,90.0,90.0,inconnue,False,normal

In [49]:
df_net_4.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2022-02-21 14:45:25.454111,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,49.0,48.0,inconnue,False,normal
1,2022-02-21 14:45:25.454114,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,49.0,48.0,inconnue,False,normal
2,2022-02-21 14:45:25.454142,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,49.0,48.0,inconnue,False,normal
3,2022-02-21 14:45:25.454260,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,system_ports,dynamic/private_ports,TCP,normal,109,inconnue,49.0,48.0,inconnue,False,normal
4,2022-02-21 14:45:25.454365,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,65,Read Holding Registers Response,49.0,48.0,[0],False,normal

In [50]:
df_net_norm.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 11:30:52.716203,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,19.0,19.0,inconnue,False,normal
1,2021-04-09 11:30:52.716499,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,65,Read Holding Registers Response,19.0,19.0,[0],False,normal
2,2021-04-09 11:30:52.717334,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,dynamic/private_ports,system_ports,Modbus,normal,66,Read Holding Registers,19.0,19.0,inconnue,False,normal
3,2021-04-09 11:30:52.717624,e6:3f:ac:c9:a8:8c,74:46:a0:bd:a7:1b,84.3.251.101,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,65,Read Holding Registers Response,19.0,19.0,[0],False,normal
4,2021-04-09 11:30:52.717952,00:80:f4:03:fb:12,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,system_ports,dynamic/private_ports,Modbus,normal,64,Read Coils Response,19.0,19.0,[0],False,normal

## Enregistrement dans PickleShare

In [51]:
data_dir = '../prep_data' 
os.makedirs(data_dir, exist_ok=True)
db = PickleShareDB(os.path.join(data_dir, 'kity'))

db['net_attack_1_clean'] = df_net_1
db['net_attack_2_clean'] = df_net_2
db['net_attack_3_clean'] = df_net_3
db['net_attack_4_clean'] = df_net_4
db['net_norm_clean'] = df_net_norm